# Generated by Django 3.2.5 on 2022-07-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.CharField(max_length=100)),
                ('Pass', models.CharField(max_length=100)),
            ],
        ),
    ]
